### ISSUE TITLE
Develop test plan for PR2 testing

### ISSUE THREAD

**Issue by EvanSchallerer** [chonny24/cloud-robotics#48]
Since we have limited time to work wit the PR2, we need to plan out how we are going to go about testing our code on it. Here are some of the things that we probably want to get out of our time with the robot/do:

- [ ] Keep stats on the robot while it runs (#54)

- [ ] Move the robot around in a given map (#55)

- [ ] Need a room/world/map to test in (#56)

- [ ] Test thresholds (#57) 

- Test with standard navigation package
    - How long should we test for? An hour? 
- Test with our package
